/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TosImport } from './routes/tos'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as MailIndexImport } from './routes/mail/index'
import { Route as MailInboxImport } from './routes/mail/inbox'

// Create/Update Routes

const TosRoute = TosImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MailIndexRoute = MailIndexImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => rootRoute,
} as any)

const MailInboxRoute = MailInboxImport.update({
  id: '/mail/inbox',
  path: '/mail/inbox',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosImport
      parentRoute: typeof rootRoute
    }
    '/mail/inbox': {
      id: '/mail/inbox'
      path: '/mail/inbox'
      fullPath: '/mail/inbox'
      preLoaderRoute: typeof MailInboxImport
      parentRoute: typeof rootRoute
    }
    '/mail/': {
      id: '/mail/'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tos': typeof TosRoute
  '/mail/inbox': typeof MailInboxRoute
  '/mail': typeof MailIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tos': typeof TosRoute
  '/mail/inbox': typeof MailInboxRoute
  '/mail': typeof MailIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tos': typeof TosRoute
  '/mail/inbox': typeof MailInboxRoute
  '/mail/': typeof MailIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/tos' | '/mail/inbox' | '/mail'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/tos' | '/mail/inbox' | '/mail'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/tos'
    | '/mail/inbox'
    | '/mail/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TosRoute: typeof TosRoute
  MailInboxRoute: typeof MailInboxRoute
  MailIndexRoute: typeof MailIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TosRoute: TosRoute,
  MailInboxRoute: MailInboxRoute,
  MailIndexRoute: MailIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/signup",
        "/tos",
        "/mail/inbox",
        "/mail/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/tos": {
      "filePath": "tos.tsx"
    },
    "/mail/inbox": {
      "filePath": "mail/inbox.tsx"
    },
    "/mail/": {
      "filePath": "mail/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
